apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: tomcat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat-container
        image: your-dockerhub-username/tomcat-custom:1.0 # Replace with your Docker image name
        ports:
        - containerPort: 8100
        env:
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m" # Optional: Adjust memory limits as needed
