apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: tomcat-app
spec:
  type: NodePort
  ports:
  - port: 8100
    targetPort: 8100
    nodePort: 30010 # Adjust as needed; NodePort must be in the range 30000-32767
  selector:
    app: tomcat-app
